_target_: equicast.model.backbones.builders.build_gnn
edges:
  - [grid, to, mesh]
  - [mesh, to, mesh]
  - [mesh, to, mesh]
  - [mesh, to, mesh]
  - [mesh, to, grid]
input_nodes: grid
hidden_dim: 204  # int(128 * 1.6)
