_target_: equicast.model.backbones.builders.build_gnn
edges:
  - [data, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, data]
input_nodes: data
hidden_dim: 204  # int(128 * 1.6)
