_target_: equicast.model.backbones.builders.build_graphcast
edges:
  - [data, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, data]
input_nodes: data
hidden_dim: 166  # int(128 * 1.3)
