_target_: equicast.model.backbones.builders.build_painn
edges:
  - [data, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, hidden]
  - [hidden, to, data]
input_nodes: data
hidden_dim: 256
