_target_: equicast.model.backbones.builders.build_painn
edges:
  - [grid, to, mesh]
  - [mesh, to, mesh]
  - [mesh, to, mesh]
  - [mesh, to, mesh]
  - [mesh, to, grid]
input_nodes: grid
hidden_dim: 256
