[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "equicast"
version = "0.1.0"
description = "Minimal package for Equicast experiments"
authors = [{ name = "Mathias Schreiner" }]
requires-python = ">=3.10"
dependencies = ['mlflow', 'anemoi-datasets']

[tool.setuptools.packages.find]
where = ["."]
