_target_: pytorch_lightning.Trainer
log_every_n_steps: 1
gradient_clip_val: 1.0
precision: bf16-mixed
callbacks:
  - _target_: equicast.callbacks.checkpoint.TimeDeltaCheckpoint
  - _target_: equicast.callbacks.step_timer.StepTimer
  - _target_: equicast.callbacks.memory_monitor.MemoryMonitor
