defaults:
  - model: from_checkpoint
  - features: base
  - _self_

dataset:
  _target_: equicast.dataset.AnemoiDataset
  path: /home/masc/storage/mini_aifs.zarr
  features: ${features}
  graph_provider:
    _target_: equicast.graph.graph_provider.StaticGraphProvider
    path: ./graph/aifs-single.pt

forecaster:
  _target_: equicast.forecaster.Forecaster
  model: ${model}
